print('String original:')
frase = 'Curso em Vídeo Python'
print(frase)
print('\nAnálise:')
print('A letra P aparece {} vez'.format(frase.count('P')))
print('A letra o aparece {} vezes'.format(frase.count('o')))
print('"Comprimento" da frase: ', len(frase))
print('Substituição: ', frase.replace('Curso', 'Método'))
print('Tem a palavra "Curso" na frase? ', 'Curso' in frase)
print('Onde está a palavra "Curso"? Na posição', frase.find('Curso'))
print('Onde está a palavra "vídeo"? Na posição', frase.lower().find('vídeo'))
print('\nSplit e join:')
dividido = frase.split()
print(dividido)
print(dividido[2][2])
print('*'.join(dividido))
