var = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(var))
print('Só tem espaço?', var.isspace())
print('É alfanumérico?', var.isalnum())
print('É apenas numérico?', var.isnumeric())
print('Contém apenas letras?', var.isalpha())
print('Está em maiúsculas?', var.isupper())
print('Está em minúsculas?', var.islower())
print('Está com a primeira letra maiúscula?', var.istitle())
